# Generated by Django 4.1.7 on 2023-05-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0007_question3_question2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
