# Generated by Django 4.1.7 on 2023-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0008_question_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='questions/'),
        ),
    ]
