# Generated by Django 4.1.7 on 2023-05-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0009_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question2',
            name='file',
            field=models.FileField(blank=True, upload_to='questions2/'),
        ),
    ]
