# Generated by Django 4.2 on 2023-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Boards", "0011_question3_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="question4",
            name='file',
            field=models.FileField(blank=True, upload_to="questions4/"),
        ),
    ]
