# Generated by Django 4.1.7 on 2023-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0012_question5'),
    ]

    operations = [
        migrations.AddField(
            model_name='question4',
            name='file',
            field=models.FileField(blank=True, upload_to='questions4/'),
        ),
    ]
