# Generated by Django 4.1.7 on 2023-05-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0012_question4_file'),
        ('Boards', '0013_question4_file'),
    ]

    operations = [
    ]
